options:
    #available: World, Region
    type: 'Region'
    #if set type to 'Region'
    region:
        #Name of World guard Regions
        name: AFKReward
    #if set type to 'World'
    world:
        #Name of world
        name: 'AFKReward'

rewards:
    '1':
        #this example will execute every 300 seconds of AFK Time
        time: 300
        #Will timer repeat?
        repeat: true
        #Command in rewards
        rewards:
            - 'say You have been AFK for {seconds} seconds!'
            - 'give {player} dirt 1 0'