options:
    #available: World, Region, BOTH
    type: 'Region'
    #if set type to 'Region'
    region:
        #Name of World guard Regions
        name:
            - AFKReward
    #if set type to 'World'
    world:
        #Name of world
        name:
            - AFKWorld
    #get other's plugin AFK status to check is player actually AFK or not
    Interaction:
        CMI: true


rewards:
    'Example':
        #name of reward
        name: example
        #What region/world this reward will apply to.
        #use "ALL" to apply to all regions
        apply-to:
            region:
                - AFKReward
            world: []
        #this example will execute every 300 seconds of AFK Time
        time: 300
        #Will timer repeat?
        repeat: true
        #Command in rewards
        rewards:
            - 'w <player> You have been AFK for <seconds> seconds!'
            - 'give <player> dirt'

Language:
    Prefix: "<GRADIENT:FBEA01>[AFK Rewards]</GRADIENT:00FDAA>&r "
    #Error Messages
    Invalid-Arguments: "<prefix><GRADIENT:FB0000>Invalid Argument. Please Check Spelling or tab complete!</GRADIENT:840000>"
    Player-Not-Found: "<prefix><GRADIENT:FB0000>Player not Found or not Online in the current Server!</GRADIENT:840000>"
    Permission-Denied: "<prefix><GRADIENT:FB0000>You do not have permission to execute this command!</GRADIENT:840000>"
    Player-Only: "<prefix><GRADIENT:FB0000>This command can only be access by player!</GRADIENT:840000>"
    Unexpected-Error: "<prefix><GRADIENT:FB0000>Unexpected Error Occurred!. Please check server console for more details.</GRADIENT:840000>"

    #Process Messages
    Command-Usage: '<prefix><GRADIENT:00FFFF>Usage: /afkreward status </GRADIENT:00FF88>'
    Command-Usage-Admin: '<prefix><GRADIENT:00FFFF>Usage: /afkreward (<reload>)(<status> <player>)(<add/subtract/set> <player> <value>)</GRADIENT:00FF88>'

    Not-in-Area: "<prefix><GRADIENT:00FFFF>You are not in AFK Reward area</GRADIENT:00FF88>"
    AFK-Notifications: "<prefix><GRADIENT:00FFFF>You are now AFK for <seconds> seconds</GRADIENT:00FF88>"

    Not-in-Area-Player: "<prefix><GRADIENT:00FFFF>Player <player> is not in AFK Reward area</GRADIENT:00FF88>"
    AFK-Notifications-Player: "<prefix><GRADIENT:00FFFF>Player <player> are now AFK for <seconds> seconds</GRADIENT:00FF88>"

    Modify-Add: "<prefix><GRADIENT:00FFFF>Successfully added <hour>h <minute>m <second>s to PlayerTimer of <player></GRADIENT:00FF88>"
    Modify-Subtract: "<prefix><GRADIENT:00FFFF>Successfully subtract <hour>h <minute>m <second>s from PlayerTimer of <player></GRADIENT:00FF88>"
    Modify-Set: "<prefix><GRADIENT:00FFFF>Successfully set <player>'s PlayerTimer to <hour>h <minute>m <second>s</GRADIENT:00FF88>"
    Modify-Notify: "<prefix><GRADIENT:00FFFF>An admin has set your PlayerTimer to <hour>h <minute>m <second>s</GRADIENT:00FF88>"

    Reloading: "<prefix><GRADIENT:E5FF67>Reloading Configuration. . .</GRADIENT:FD85FC>"
    Reloaded: "<prefix><GRADIENT:E5FF67>Successfully reloaded configuration</GRADIENT:FD85FC>"

    #This Message showed in console
    Loading: "<GRADIENT:E5FF67>Loading Configuration. . .</GRADIENT:FD85FC>"
    Loaded: "<GRADIENT:E5FF67>Successfully loaded configuration</GRADIENT:FD85FC>"
